### PR TITLE
Bump CI to GHC 9.4 and latest actions, limit transformers < 0.6

### PR DESCRIPTION
**Pull request by andreasabel**
The package does not build with `transformers-0.6.*`, so added an upper bound via a Hackage revision: https://hackage.haskell.org/package/unbound-generics-0.4.2/revisions/

CI ran here: https://github.com/andreasabel/unbound-generics/actions/runs/4811908537

CI fails to install GHC 7.10, reported this error upstream:
- https://github.com/haskell/actions/issues/233

### CODE REVIEW

**Comment by lambdageek** [comment]
Maybe I should drop GHC 7.10 support?

**Comment by andreasabel** [comment]
> Maybe I should drop GHC 7.10 support?

I would suggest this, as this GHC is now pretty ancient.
Not sure if `ghcup` will restore support for GHC 7.10:
- https://github.com/haskell/ghcup-hs/issues/821

**Comment by lambdageek** [comment]
@andreasabel could you remove GHC 7.10 as part of this PR, please.  If not, I'll try to push some commits later today.

**Comment by andreasabel** [comment]
Done.  I think GHC 7.10 won't be fixed upstream:
- https://gitlab.haskell.org/ghc/ghc/-/issues/20782

**Pull request merged**
